export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const CREATE_CATEGORY = 'CREATE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const CREATE_EXPENSE = 'CREATE_EXPENSE';
